# PD position controller parameters (origiinal)
position_gain: {x: 4, y: 4, z: 4}
velocity_gain: {x: 2.7, y: 2.7, z: 2.7}
position_integral_gain: {x: 0, y: 0, z: 0}
attitude_gain: {x: 2, y: 3, z: 0.1}
angular_rate_gain: {x: 0.52, y: 0.62, z: 0.02}
