# Pelican vehicle parameters
scissors_mass: 0.075
box_mass: 0.65
rotor_mass: 0.05
rotor_unit_mass: 0.4
rotor_ext_len: 0.25
battery_mass: 0.163
battery_dim: {x: 0.1, y: 0.03, z: 0.03}
box_hat: {x: 0.2, y: 0.2, z: 0.2}
box_dim: {x: 0.5, y: 0.5, z: 0.3}

# angle should be expressed in rad
# direction 1 means counter clockwise, -1 clockwise
# The order of the rotors matters for the calculation of the allocation matrix.

# Simulation
# rotor_configuration:
#   '0': {angle: 0, arm_length: 1.2, rotor_force_constant: 9.9865e-06, rotor_moment_constant: 1.6e-2, direction: -1.0}
#   '1': {angle: 1.57079632679, arm_length: 0.8, rotor_force_constant: 9.9865e-06, rotor_moment_constant: 1.6e-2, direction: 1.0}
#   '2': {angle: 3.14159265359, arm_length: 1.2, rotor_force_constant: 9.9865e-06, rotor_moment_constant: 1.6e-2, direction: -1.0}
#   '3': {angle: -1.57079632679, arm_length: 0.8, rotor_force_constant: 9.9865e-06, rotor_moment_constant: 1.6e-2, direction: 1.0}

# Hardware
rotor_configuration:
  '0': {angle: -0.7839163, arm_length: 0.45, rotor_force_constant: 5.54858e-04, rotor_moment_constant: 0.016, direction: 1.0}
  '1': {angle: 2.3561944, arm_length: 0.45, rotor_force_constant: 5.54858e-04, rotor_moment_constant: 0.016, direction: 1.0}
  '2': {angle: -2.3561944, arm_length: 0.45, rotor_force_constant: 5.54858e-04, rotor_moment_constant: 0.016, direction: -1.0}
  '3': {angle: 0.7839163, arm_length: 0.45, rotor_force_constant: 5.54858e-04, rotor_moment_constant: 0.016, direction: -1.0}
